version: "3.9"

services:
    rabbit:
      image: rabbitmq:management
      container_name: rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
        - 5672:5672
        - 15672:15672

    mongo:
      image: mongo:latest
      container_name: mongodb
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: root-db
      ports:
        - 27017:27017
      volumes:
        - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    mongo-express:
      image: mongo-express
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_BASICAUTH_USERNAME: user
        ME_CONFIG_BASICAUTH_PASSWORD: pass
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
      links:
        - mongo